config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'home/index'
  root to: "home#index"
  resources :products
  resources :categories

  devise_for :users

  namespace :superadmin do
  	resources :users do
  		collection do
  			get :admins
  		end
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user,optional: true
    has_many_attached :images	
	enum category: [:electronics, :footwear, :jewellery, :books, :fashion_acessories, :sports_good]
	ratyrate_rateable "best" , "low", "average"
	has_many :ratings,  foreign_key: 'rateable_id', class_name: 'Rate' 

	def overall_ratings(product)
		
        array = Rate.where(rateable_id: id, rateable_type: 'Product')
		stars = array.map {|product| product.stars }
		star_count = stars.count
		stars_total = stars.inject(0){|sum,x| sum + x }
		score = stars_total / (star_count.nonzero? || 1)
	end

	

    def self.search(search =nil,search1=nil)		
		if search.present? && search1.present?
			where("name like ? and category like ?", "%#{search}%", "%#{search1}%")
		elsif search.present?		
			where("name like ? ", "%#{search}%")	
		elsif search1.present?

			where("category like ? ", "%#{search1}%")
		else
			products = Product.all
		end
	end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  belongs_to :product, foreign_key: :rateable_id

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:superadmin, :admin, :user]
  has_many :products, dependent: :destroy
  belongs_to :admin, :optional => true, class_name: 'User'
  #has_many :ratings, foreign_key: "rater_id" ,class_name: "Rate"
   has_one :page
  ratyrate_rater
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index
		@user = User.admin
		render 'superadmin/users/index'
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session

    include Rails.application.routes.url_helpers
    def index
    	@product = product.all
    	#image_url = rails_blob_path(@product.images, disposition: "attachment", only_path: true)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :verify_authenticity_token  
	before_action :authenticate_user! , except: [:index]

	def index
		@products = Product.search(params[:search], params[:search1])		
		html =render_to_string :partial => 'products/category', locals: {:search => @products}
		respond_to do |format|
			format.html
			format.json { render json: {html: html} }
		end
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
        if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def show
		@product = Product.find (params[:id])

    end

	def edit
		@product = Product.find (params[:id])
		
    end

    def update
    	@product = Product.find(params[:id])
    	
        if @product.update(product_params)
    		redirect_to @product
    	else
    		render 'edit'
    	end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end



	private
	def product_params
    	params.require(:product).permit(:name, :category, images:[])
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController
	skip_before_action :verify_authenticity_token

  def create

    if current_user
    
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]
       @product = obj
     
    end

    respond_to do |format|
      # format.html
      format.js 
    end
  end
end

app/controllers/superadmin/superadmin_application_controller.rb
module Superadmin
  class SuperadminApplicationController < ApplicationController
  	
  	protect_from_forgery with: :exception

    before_action :authenticate_user!
    before_action :authenticate_superadmin

    def authenticate_superadmin
      if current_user.superadmin?
        true
      else
      	redirect_to root_path
        
      end
    end
   end
end

app/controllers/superadmin/users_controller.rb
class Superadmin::UsersController < Superadmin::SuperadminApplicationController
	
    def index
		@users = User.all
    end

    def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.save
		redirect_to superadmin_users_path
	end

 	def edit
 		@user = User.find (params[:id])
 	end

 	def update
 		@user = User.find (params[:id])
 		if @user.update(user_params)
 		   redirect_to superadmin_users_path
 			
 		else
 			render 'edit'
 		end
 	end

 	def destroy
 		@user = User.find (params[:id])
 		@user.destroy
 		redirect_to superadmin_users_path
 	end

 	def admins
 		@users = User.admin
 		render "superadmin/users/index"
 	end

	private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
	
	
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
.jumbotron.jumbotron-fluid.mt-2
  .container
    h1 Online Shopping
    p Online shopping is a form of electronic commerce which allows consumers to directly buy goods or services from a seller over the Internet.

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light
  a.navbar-brand.logo-text href="#"  ONLINE STORE
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        a.nav-link href="/"  Home
      li.nav-item
        = link_to "Products", products_path, class: "nav-link" 
      li.nav-item
         -if (user_signed_in? && ( current_user.role == 'superadmin')) 
           = link_to "Users",  superadmin_users_path, class: "nav-link" 
       
      li.nav-item
        a.nav-link href="/"  About
    ul.navbar-nav.my-lg-0
      - if user_signed_in? 
         li
         = link_to('Logout', destroy_user_session_path, class: "btn btn-secondary", method: :delete) 
      -else 
         li 
          = link_to "Sign up", new_user_registration_path, class: "btn btn-secondary", :style =>"margin-right:20px" 
         li
          = link_to 'Login', new_user_session_path,class: "btn btn-secondary" 

app/views/layouts/application.html.slim
doctype html
html
  head
    title OnlineStore
    = csrf_meta_tags 
    = csp_meta_tag 
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    script crossorigin="anonymous" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" src="https://code.jquery.com/jquery-3.4.1.js" 
  body
    = render 'layouts/header' 
    = yield
  = javascript_include_tag 'application', 'data-turbolinks-track': 'false' 

app/views/products/_category.html.slim
-@products.each do |product| 
	tr
	  td.ajax
	    span.text-field
	       = product.name 
	    input.edit-input[type="text" data-id="= product.id  "]
	  td
	     = product.category
	  td
	     = product.image 
	  td
	     = link_to 'show', product_path(product),class: "btn btn-warning" 
	  td
	      -if (user_signed_in? && (product.user_id == current_user.id))  
	           = link_to 'edit', edit_product_path(product),class: "btn btn-primary" 
	  td
	    = link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" 

app/views/products/_form.html.slim
= form_with model: @product, local: true do |form|  
  -if @product.errors.any? 
   #error_explanation
   h2 = "prohibited this product from being saved:"
   ul
    -@product.errors.full_messages.each do |msg|  
      li
       = msg
  
  
  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control' 
  .form-group
    = form.label :category 
    = form.select :category, options_for_select([ 'electronics', 'footwear', 'jewellery', 'books', 'fashion_acessories',"sports_good" ]),{}, :class => 'form-control',:prompt => 'Select One'
  .form-group
    = form.label :images 
    br/
    = form.file_field :images, multiple: true 
  div
      = form.submit "Create Product", class: "btn btn-primary"

app/views/products/edit.html.slim
.container
  .col-md-6.offset-md-3
    .card.mt-5
      h2.card-header
         Edit Product
      .card-body
        = render 'form' 

app/views/products/index.html.slim
.container
  form
     = text_field_tag :search, params[:search], placeholder: "Search Products", onkeypress: "myFunction()", class: 'mr-4' 
     = select_tag(:search1, options_for_select([[ "electronics" ,0], ["footwear",1], ["jewellery",2], ["books",3], ["fashion_acessories",4],["sports_goods",5]],params[:search1]), :prompt => "Select One", onchange: "myFunction()" ) 
  .card.mt-5
    h2.card-header
       All Products
    table.table.mb-0
      tr
        th
           Name
        th
           Category
        th
           Image
        th[colspan="2"]
           Action
      tbody.data
        = render 'products/category'  
  br
  = link_to('Add product', new_product_path ,class: "btn btn-primary") 

app/views/products/new.html.slim
.container
  .col-md-6.offset-md-3
    .card.mt-5
      h2.card-header
         New Product
      .card-body
        = render 'form' 

app/views/products/show.html.slim
.container
  .col-md-6.offset-md-3
    .card.mt-5
      .card-body
        .card-image.text-center
          -if @product.images.attached?   
            -@product.images.each do |image| 
             = image_tag (image)  
        .card-title.text-center
            h2
             = @product.name 
        p
            strong
              |Category:
            b
             = @product.category 
        h3
           Ratings
         	  Best = rating_for @product, 'best' 
      

app/views/rater/_star_show.html.slim
.mr-4
  b
     Original Score:
  .ratings_container
    span.rate_img
       = imdb_style_rating_for @product, "original_score", disable_after_rate: true, imdb_avg: true 
    span.rate_score
      = number_with_precision(@product. overall_ratings(@product), precision: 1) 
    -@product.ratings.each do |ratings| 
	  = ratings.rater.first_name %> 
	  = rating_for @product, 'best' 

app/views/rater/create.js.erb
$("#content").html("<%= escape_javascript render(partial: 'star_show')%>");

app/views/superadmin/users/_form.html.slim
.col-md-4.offset-md-4
  .card.mt-5
    h2.card-header.text-center
       Add User
    .card-body
        = form_for ([:superadmin, @user]) do |f| 
      .form-group
          = f.label :first_name 
        br
          = f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control"  
      .form-group
          = f.label :last_name 
        br
          = f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control" 
      .form-group
         = f.label :email 
        br
         = f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control"  
      .form-group
         = f.label :password   -if @minimum_password_length 
        em
           (= @minimum_password_length  characters minimum)
          
        br
        = f.password_field :password, autocomplete: "new-password", class: "form-control" 
      .form-group
          = f.label :password_confirmation
        br
        = f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control"  
      .form-group
          = f.label :role 
        br
        = f.select :role, options_for_select([ 'superadmin', 'admin', 'user' ]), {}, :class => 'form-control',:include_blank => 'Select One'  
      .actions
        = f.submit "create user" , class: "btn btn-primary" 
    

app/views/superadmin/users/edit.html.slim
= render 'form' 

app/views/superadmin/users/index.html.slim
.container
  = link_to 'Add User', new_superadmin_user_path, class: 'btn btn-primary'  
  .card.mt-4
    h1.card-header
    | All users
    table.table.table-bordered.mb-0
      tr
        th
           First Name
        th
           Last Name
        th
           Email
        th[colspan="2"]
           Action
         -@users.each do |user| 
      tr
        td
          = user.first_name
        td
          = user.last_name 
        td
          = user.email 
        td
          = link_to 'Edit', edit_superadmin_user_path(user) 
        td
          = link_to 'Destroy', superadmin_user_path(user) ,method: :delete, data: { confirm: 'Are you sure?' } 
    

app/views/superadmin/users/new.html.slim
= render 'form' 

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>